### ISSUE TITLE
'make install' does not work

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/pciedummy-driver#9]
When running 'sudo make install' on Ubuntu 20.04 the process fails with the following error message:
```
make -f ./scripts/Makefile.build obj=arch/x86/tools relocs
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
```
The dkms installation via debian package is working, though.

Better change the whole installation process to dkms (like gpcieuni)

**Comment by phako** [comment]
Same as #1
